version: 2
jobs:
  build:
    machine: true
    # machine: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - restore_cache:
          keys:
            - snakemake-{{ checksum ".circleci/setup.sh" }}

      - run:
          name: Update PATH
          command: "echo 'export PATH=${PWD}/miniconda/bin:${PATH}' >> ${BASH_ENV}"

      - run:
          name: Setup Conda
          command: bash .circleci/setup.sh

      - save_cache:
          key: snakemake-{{ checksum ".circleci/setup.sh" }}
          paths:
            - miniconda

      - run:
          name: Run Unit testing
          command: make all-unit-tests

      - run:
          name: Run System testing
          command: make ci-tests
