name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * 0'

jobs:
  conda_setup:
    name: Conda Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup conda
        run: bash .github/workflows/setup.sh
  pipeline_test:
    name: Snakemake-workflow tests
    runs-on: ubuntu-latest
    needs: conda_setup
    steps:
      - uses: actions/checkout@v1
      - name: Setup workflow environment
        run: make conda-install
      - name: Scripts unit-testing
        run: make all-unit-tests
      - name: Run Snakemake-workflow
        run: make test-conda-report.html
      - name: Clean
        run: make clean
      - name: Run workflow in Singularity
        run: make test-singularity-report.html
